# Generated by Django 4.1.1 on 2023-01-24 23:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
        migrations.RemoveField(
            model_name='post',
            name='publish',
        ),
    ]
