# Generated by Django 4.1.1 on 2023-01-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_publish'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='snippet',
            field=models.CharField(default='we are processing', max_length=255),
        ),
    ]
