# Generated by Django 4.1.1 on 2023-01-25 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_post_tagged'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='tagged',
            new_name='tags',
        ),
    ]
